name: "dbt docs deploy"

# Triggers
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-dbt-docs-from-main-branch:
    permissions:
      contents: "read"
      id-token: "write"
      pages: write      # to deploy to Pages
    runs-on: ubuntu-latest
    

    steps:
                  #checkout the code
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v2

      - name: "Step 01 - Pull down elementary docs"
        id: step-02
        run: |
          ls -ltra
          cat index.html 
          mkdir elementary_docs
          mv index.html ./elementary_docs
          

      - name: "Step 02 - Upload pages to artifact"
        id: step-03
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ${{ github.workspace }}/elementary_docs
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
